<?php
defined('BASEPATH') or exit('No direct script access allowed');
require_once APPPATH . 'libraries/LeadDiscovery/LeadDiscoveryProvider.php';
require_once APPPATH . 'libraries/LeadDiscovery/ProviderException.php';
require_once APPPATH . 'libraries/LeadDiscovery/GooglePlacesProvider.php';
require_once APPPATH . 'libraries/LeadDiscovery/ProviderRegistry.php';
require_once APPPATH . 'libraries/LeadDiscovery/Deduplicator.php';

/** Organization-scoped Lead Discovery API with pluggable, normalized providers. */
class Api_lead_discovery extends Api_controller
{
    private array $user; private string $org;
    /** Resolve the workspace only from the authenticated user's memberships; no client supplied org ID is trusted. */
    private function guard(): bool {
        $u=$this->requirePermission('system.authenticated'); if (!$u) return false; $this->user=$u;
        $requested=(string)($this->input->get_request_header('X-Lead-Organization') ?: '');
        $memberships=$this->db->where('user_id',(int)$u['id'])->order_by('created_at','ASC')->get('lead_organization_members')->result_array();
        // First authenticated use receives a private workspace. Teams can later add explicit memberships.
        if (!$memberships) { $id='org-'.(int)$u['id']; $now=$this->now(); $this->db->replace('lead_organizations',['id'=>$id,'name'=>($u['email'] ?? 'My').' workspace','created_at'=>$now]); $this->db->replace('lead_organization_members',['organization_id'=>$id,'user_id'=>(int)$u['id'],'role'=>'owner','created_at'=>$now]); $memberships=[['organization_id'=>$id,'role'=>'owner']]; }
        $chosen=$requested ?: $memberships[0]['organization_id'];
        foreach($memberships as $m) if(hash_equals((string)$m['organization_id'],$chosen)) { $this->org=$chosen; return true; }
        $this->jsonError('forbidden organization workspace',403); return false;
    }
    public function workspaces(){ if(!$this->guard())return; $rows=$this->db->select('o.id,o.name,m.role')->from('lead_organizations o')->join('lead_organization_members m','m.organization_id=o.id')->where('m.user_id',(int)$this->user['id'])->get()->result_array(); $this->json(['workspaces'=>$rows,'activeOrganizationId'=>$this->org]); }
    public function providers(){ if(!$this->guard())return; $this->json(['providers'=>(new \LeadDiscovery\ProviderRegistry([new \LeadDiscovery\GooglePlacesProvider()]))->health()]); }
    private function id(): string { return bin2hex(random_bytes(16)); }
    private function now(): string { return gmdate('c'); }
    private function recordActivity(?string $lead, string $type, array $detail=[]): void { $this->db->insert('lead_activities',['id'=>$this->id(),'lead_id'=>$lead,'organization_id'=>$this->org,'actor_id'=>$this->user['id'],'type'=>$type,'detail'=>json_encode($detail),'created_at'=>$this->now()]); }
    private function lead(string $id): ?array { return $this->db->get_where('leads',['id'=>$id,'organization_id'=>$this->org],1)->row_array() ?: null; }
    private function safeCsv(string $v): string { return preg_match('/^[=+\-@]/', $v) ? "'".$v : $v; }

    public function search() {
        if(!$this->guard())return; $b=$this->jsonBody(); $q=trim((string)($b['query']??''));
        if(strlen($q)<3 || strlen($q)>300)return $this->jsonError('query must be 3–300 characters');
        $started=microtime(true); $providerName=(string)($b['provider']??'google_places'); $error=null; $raw=[]; $providerStatus='DISABLED';
        try { $registry=new \LeadDiscovery\ProviderRegistry([new \LeadDiscovery\GooglePlacesProvider()]); $provider=$registry->get($providerName); $providerStatus=$provider->healthCheck()['status']; $raw=$provider->searchBusinesses(['query'=>$q,'limit'=>$b['limit']??20]); }
        catch(\LeadDiscovery\ProviderException $e) { $error=$e->getMessage(); $providerStatus=$e->httpStatus===422?'PLANNED':'DISABLED'; }
        $new=0;$dupes=0;$candidateCount=0;$results=[];
        foreach($raw as $p){ $sid=(string)$p['sourceId']; $existing=$this->db->get_where('leads',['organization_id'=>$this->org,'source'=>$providerName,'source_id'=>$sid],1)->row_array(); $record=['organization_id'=>$this->org,'source'=>$providerName,'source_id'=>$sid,'name'=>$p['name'],'category'=>$p['category'],'address'=>$p['address'],'phone'=>$p['phone'],'website'=>$p['website'],'latitude'=>$p['latitude'],'longitude'=>$p['longitude'],'metadata'=>json_encode($p['metadata']),'updated_at'=>$this->now()];
          if($existing){$this->db->where('id',$existing['id'])->where('organization_id',$this->org)->update('leads',$record);$record['id']=$existing['id'];$dupes++;$this->recordActivity($existing['id'],'DUPLICATE_DETECTED',['rule'=>'provider_source_id']);} else {$record+=['id'=>$this->id(),'status'=>'new','owner_id'=>null,'created_at'=>$this->now()];$this->db->insert('leads',$record);$new++;$this->recordActivity($record['id'],'LEAD_DISCOVERED',['query'=>$q,'provider'=>$providerName]);} $candidateCount+=(new \LeadDiscovery\Deduplicator($this->db))->detect($record,$this->org); $results[]=$record;
        }
        $this->db->insert('search_history',['id'=>$this->id(),'organization_id'=>$this->org,'user_id'=>$this->user['id'],'query'=>$q,'provider'=>$providerName,'filters'=>json_encode(['limit'=>$b['limit']??20]),'results_returned'=>count($raw),'new_leads_created'=>$new,'duplicates_detected'=>$dupes+$candidateCount,'errors'=>$error,'duration_ms'=>(int)((microtime(true)-$started)*1000),'created_at'=>$this->now()]);
        if($error)return $this->jsonError($error,503,['providerStatus'=>$providerStatus]); $this->json(['provider'=>$providerName,'providerStatus'=>$providerStatus,'results'=>$results,'newLeadsCreated'=>$new,'duplicatesDetected'=>$dupes+$candidateCount,'duplicateCandidatesCreated'=>$candidateCount]);
    }
    public function leads($id=null){if(!$this->guard())return;if($id){$x=$this->lead($id);return $x?$this->json($x):$this->jsonError('lead not found',404);} $this->db->where('organization_id',$this->org);if($s=$this->input->get('status'))$this->db->where('status',$s);$this->json(['leads'=>$this->db->order_by('updated_at','DESC')->limit(250)->get('leads')->result_array()]);}
    public function collections($id=null){
        if(!$this->guard())return;$method=$this->input->method(true);
        if($id&&$method==='PATCH'){$b=$this->jsonBody();$name=trim((string)($b['name']??''));if(!$name||strlen($name)>150)return $this->jsonError('name must be 1–150 characters');$this->db->where(['id'=>$id,'organization_id'=>$this->org])->update('collections',['name'=>$name,'updated_at'=>$this->now()]);return $this->json(['ok'=>true]);}
        if($id&&$method==='DELETE'){$this->db->where('collection_id',$id)->delete('collection_leads');$this->db->where(['id'=>$id,'organization_id'=>$this->org])->delete('collections');return $this->json(['ok'=>true]);}
        if($method==='POST'){$name=trim((string)($this->jsonBody()['name']??''));if(!$name||strlen($name)>150)return $this->jsonError('name must be 1–150 characters');$x=['id'=>$this->id(),'organization_id'=>$this->org,'name'=>$name,'created_at'=>$this->now(),'updated_at'=>$this->now()];$this->db->insert('collections',$x);return $this->json($x,201);}
        $rows=$this->db->select('c.*, COUNT(cl.lead_id) leadCount')->from('collections c')->join('collection_leads cl','cl.collection_id=c.id','left')->where('c.organization_id',$this->org)->group_by('c.id')->order_by('c.name')->get()->result_array();$this->json(['collections'=>$rows]);
    }
    public function collection_leads($collection,$lead=null){
        if(!$this->guard())return;if(!$this->db->get_where('collections',['id'=>$collection,'organization_id'=>$this->org],1)->row_array())return $this->jsonError('collection not found',404);
        if($this->input->method(true)==='GET')return $this->json(['leads'=>$this->db->select('l.*')->from('leads l')->join('collection_leads cl','cl.lead_id=l.id')->where(['cl.collection_id'=>$collection,'l.organization_id'=>$this->org])->get()->result_array()]);
        $ids=$lead?[$lead]:($this->jsonBody()['leadIds']??[]);if(!is_array($ids)||!$ids||count($ids)>200)return $this->jsonError('leadIds must contain 1–200 leads');$added=0;$removed=0;
        foreach(array_unique($ids) as $leadId){if(!$this->lead((string)$leadId))return $this->jsonError('lead not found',404,['leadId'=>$leadId]);if($this->input->method(true)==='DELETE'){$this->db->where(['collection_id'=>$collection,'lead_id'=>$leadId])->delete('collection_leads');$removed+=$this->db->affected_rows();$this->recordActivity($leadId,'LEAD_REMOVED_FROM_COLLECTION',['collectionId'=>$collection]);}else{$exists=$this->db->where(['collection_id'=>$collection,'lead_id'=>$leadId])->count_all_results('collection_leads');if(!$exists){$this->db->insert('collection_leads',['collection_id'=>$collection,'lead_id'=>$leadId]);$added++;$this->recordActivity($leadId,'LEAD_ADDED_TO_COLLECTION',['collectionId'=>$collection]);}}}
        $this->json(['ok'=>true,'added'=>$added,'removed'=>$removed]);
    }
    public function status($id){if(!$this->guard())return;$x=$this->lead($id);$v=$this->jsonBody()['status']??'';if(!$x)return $this->jsonError('lead not found',404);if(!in_array($v,['new','contacted','qualified','disqualified','converted'],true))return $this->jsonError('invalid status');$this->db->where('id',$id)->update('leads',['status'=>$v,'updated_at'=>$this->now()]);$this->recordActivity($id,'STATUS_CHANGED',['from'=>$x['status'],'to'=>$v]);$this->json(['ok'=>true]);}
    public function owner($id){if(!$this->guard())return;if(!$this->lead($id))return $this->jsonError('lead not found',404);$owner=$this->jsonBody()['ownerId']??null;if($owner!==null&&!ctype_digit((string)$owner))return $this->jsonError('ownerId must be an integer or null');$this->db->where('id',$id)->update('leads',['owner_id'=>$owner,'updated_at'=>$this->now()]);$this->recordActivity($id,$owner===null?'OWNER_REMOVED':'OWNER_ASSIGNED',['ownerId'=>$owner]);$this->json(['ok'=>true]);}
    public function notes($id){if(!$this->guard())return;if(!$this->lead($id))return $this->jsonError('lead not found',404);if($this->input->method(true)==='POST'){$body=trim((string)($this->jsonBody()['body']??''));if(!$body||strlen($body)>4000)return $this->jsonError('note must be 1–4000 characters');$n=['id'=>$this->id(),'lead_id'=>$id,'organization_id'=>$this->org,'author_id'=>$this->user['id'],'body'=>$body,'created_at'=>$this->now()];$this->db->insert('lead_notes',$n);$this->recordActivity($id,'NOTE_ADDED',[]);return $this->json($n,201);}$this->json(['notes'=>$this->db->where(['lead_id'=>$id,'organization_id'=>$this->org])->order_by('created_at','DESC')->get('lead_notes')->result_array()]);}
    public function activity($id){if(!$this->guard())return;if(!$this->lead($id))return $this->jsonError('lead not found',404);$this->json(['activity'=>$this->db->where(['lead_id'=>$id,'organization_id'=>$this->org])->order_by('created_at','DESC')->get('lead_activities')->result_array()]);}
    public function duplicates($resolve=false){
        if(!$this->guard())return;
        if(!$resolve){$rows=$this->db->select('d.*, a.name leadAName, b.name leadBName')->from('duplicate_candidates d')->join('leads a','a.id=d.lead_a_id')->join('leads b','b.id=d.lead_b_id')->where(['d.organization_id'=>$this->org,'d.status'=>'open'])->order_by('d.created_at','DESC')->get()->result_array();return $this->json(['duplicates'=>$rows]);}
        $b=$this->jsonBody();$id=(string)($b['candidateId']??'');$action=(string)($b['action']??'');
        if(!in_array($action,['keep_a','keep_b','merge','ignore'],true))return $this->jsonError('invalid duplicate resolution');
        $c=$this->db->get_where('duplicate_candidates',['id'=>$id,'organization_id'=>$this->org],1)->row_array();if(!$c)return $this->jsonError('duplicate candidate not found',404);
        $a=$this->lead($c['lead_a_id']);$bLead=$this->lead($c['lead_b_id']);if(!$a||!$bLead)return $this->jsonError('candidate leads no longer exist',409);
        if($action==='merge') { $canonical=$a;$duplicate=$bLead; foreach(['category','address','city','region','country','phone','website','latitude','longitude'] as $field) if(empty($canonical[$field])&&!empty($duplicate[$field]))$canonical[$field]=$duplicate[$field]; $canonical['updated_at']=$this->now();$this->db->where('id',$canonical['id'])->update('leads',$canonical);$this->archiveDuplicate($duplicate,$canonical['id'],'merged');$this->recordActivity($canonical['id'],'DUPLICATE_RESOLVED',['candidateId'=>$id,'action'=>'merge','mergedLeadId'=>$duplicate['id']]); }
        elseif($action==='keep_a'||$action==='keep_b') { $keep=$action==='keep_a'?$a:$bLead;$discard=$action==='keep_a'?$bLead:$a;$this->archiveDuplicate($discard,$keep['id'],'discarded');$this->recordActivity($keep['id'],'DUPLICATE_RESOLVED',['candidateId'=>$id,'action'=>$action,'discardedLeadId'=>$discard['id']]); }
        else $this->recordActivity($a['id'],'DUPLICATE_RESOLVED',['candidateId'=>$id,'action'=>'ignore']);
        $this->db->where('id',$id)->update('duplicate_candidates',['status'=>'resolved']);$this->db->insert('duplicate_resolutions',['id'=>$this->id(),'candidate_id'=>$id,'organization_id'=>$this->org,'resolver_id'=>$this->user['id'],'action'=>$action,'created_at'=>$this->now()]);$this->json(['ok'=>true]);
    }
    private function archiveDuplicate(array $lead,string $keptId,string $reason):void { $metadata=json_decode($lead['metadata']??'{}',true)?:[];$metadata['duplicateResolution']=['keptLeadId'=>$keptId,'reason'=>$reason,'at'=>$this->now()];$this->db->where('id',$lead['id'])->update('leads',['status'=>'disqualified','metadata'=>json_encode($metadata),'updated_at'=>$this->now()]);$this->recordActivity($lead['id'],'DUPLICATE_RESOLVED',['keptLeadId'=>$keptId,'action'=>$reason]); }
    public function coverage(){if(!$this->guard())return;$all=$this->db->where('organization_id',$this->org)->get('leads')->result_array();$n=count($all);$fields=['name'=>'Business Name','address'=>'Address','category'=>'Category','phone'=>'Phone','website'=>'Website'];$out=[];foreach($fields as $f=>$label){$filled=count(array_filter($all,fn($x)=>!empty($x[$f])));$out[]=['key'=>$f,'field'=>$label,'coverage'=>$n?round(100*$filled/$n,1):0,'missing'=>$n-$filled];}$missing=(string)$this->input->get('missing');if($missing!==''&&!isset($fields[$missing]))return $this->jsonError('invalid missing field');$missingLeads=$missing===''?[]:array_values(array_filter($all,fn($x)=>empty($x[$missing])));$this->json(['leadCount'=>$n,'fields'=>$out,'missingField'=>$missing?:null,'missingLeads'=>$missingLeads]);}
    public function history(){if(!$this->guard())return;$this->json(['history'=>$this->db->where('organization_id',$this->org)->order_by('created_at','DESC')->limit(100)->get('search_history')->result_array()]);}
    public function summary(){if(!$this->guard())return;$rows=$this->db->select('status, COUNT(*) total')->where('organization_id',$this->org)->group_by('status')->get('leads')->result_array();$this->json(['pipeline'=>$rows]);}
    public function pipeline(){if(!$this->guard())return;$statuses=['new','contacted','qualified','disqualified','converted'];$columns=array_fill_keys($statuses,[]);foreach($this->db->where('organization_id',$this->org)->order_by('updated_at','DESC')->get('leads')->result_array() as $lead)$columns[$lead['status']][]=$lead;$this->json(['statuses'=>$statuses,'columns'=>$columns]);}
    public function export($mode='json'){if(!$this->guard())return;$b=$this->jsonBody();$this->db->where('l.organization_id',$this->org)->from('leads l');if(!empty($b['collectionId']))$this->db->join('collection_leads cl','cl.lead_id=l.id')->where('cl.collection_id',$b['collectionId']);foreach(['status','owner_id','country','category'] as $f)if(isset($b[$f])&&$b[$f]!=='')$this->db->where('l.'.$f,$b[$f]);if(!empty($b['from']))$this->db->where('l.created_at >=',$b['from']);if(!empty($b['to']))$this->db->where('l.created_at <=',$b['to']);$leads=$this->db->get()->result_array();if($mode==='preview'){foreach($leads as &$row)foreach($row as $k=>$v)$row[$k]=is_string($v)?$this->safeCsv($v):$v;return $this->json(['rows'=>array_slice($leads,0,25),'count'=>count($leads),'csvSafe'=>true]);}$format=$mode==='csv'?'csv':($b['format']??'json');$this->db->insert('export_history',['id'=>$this->id(),'organization_id'=>$this->org,'user_id'=>$this->user['id'],'format'=>$format,'filters'=>json_encode($b),'lead_count'=>count($leads),'created_at'=>$this->now()]);foreach($leads as $x)$this->recordActivity($x['id'],'LEAD_EXPORTED',['format'=>$format]);if($format==='csv'){$keys=['name','category','address','city','country','phone','website','status'];$lines=[implode(',',$keys)];foreach($leads as $l){$lines[]=implode(',',array_map(fn($k)=>'"'.str_replace('"','""',$this->safeCsv((string)($l[$k]??''))).'"',$keys));}$this->output->set_content_type('text/csv')->set_header('Content-Disposition: attachment; filename="leads.csv"')->set_output(implode("\r\n",$lines));return;}$this->json(['leads'=>$leads,'count'=>count($leads)]);}
}
