-- PostgreSQL source-of-truth schema. Redis must never hold the only copy of lead data.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS organization_members (organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('owner','admin','member')), PRIMARY KEY(organization_id,user_id));
CREATE TYPE lead_status AS ENUM ('new','contacted','qualified','disqualified','converted');
CREATE TABLE IF NOT EXISTS leads (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, source text NOT NULL, source_id text NOT NULL, name text NOT NULL, category text, address text, city text, region text, country text, phone text, website text, latitude double precision, longitude double precision, status lead_status NOT NULL DEFAULT 'new', owner_id uuid REFERENCES users(id) ON DELETE SET NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,source,source_id));
CREATE INDEX IF NOT EXISTS leads_org_status_idx ON leads(organization_id,status); CREATE INDEX IF NOT EXISTS leads_org_owner_idx ON leads(organization_id,owner_id); CREATE INDEX IF NOT EXISTS leads_org_created_idx ON leads(organization_id,created_at DESC);
CREATE TABLE IF NOT EXISTS collections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,name));
CREATE TABLE IF NOT EXISTS collection_leads (collection_id uuid REFERENCES collections(id) ON DELETE CASCADE, lead_id uuid REFERENCES leads(id) ON DELETE CASCADE, PRIMARY KEY(collection_id,lead_id));
CREATE TABLE IF NOT EXISTS lead_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE, author_id uuid NOT NULL REFERENCES users(id), body text NOT NULL CHECK(length(body) BETWEEN 1 AND 4000), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS lead_activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, lead_id uuid REFERENCES leads(id) ON DELETE CASCADE, actor_id uuid REFERENCES users(id), type text NOT NULL, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS search_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id), query text NOT NULL, provider text NOT NULL, filters jsonb NOT NULL DEFAULT '{}', results_returned int NOT NULL, new_leads_created int NOT NULL, duplicates_detected int NOT NULL, errors jsonb, duration_ms int NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS duplicate_candidates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, lead_a_id uuid NOT NULL REFERENCES leads(id), lead_b_id uuid NOT NULL REFERENCES leads(id), rule_name text NOT NULL, confidence numeric(4,3) NOT NULL CHECK(confidence BETWEEN 0 AND 1), status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS duplicate_resolutions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), candidate_id uuid NOT NULL REFERENCES duplicate_candidates(id), organization_id uuid NOT NULL REFERENCES organizations(id), resolver_id uuid NOT NULL REFERENCES users(id), action text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS export_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id), format text NOT NULL CHECK(format IN ('json','csv')), filters jsonb NOT NULL, lead_count int NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
