<?php
namespace Aegis\LangLearn;

/**
 * VOCABULARY BANK — authored, verifiable vocabulary per language.
 *
 * Tuple: [word, translation, pronunciation|null, exampleSentence|null, category, level]
 * Pronunciation is only filled where a confident romanization exists
 * (non-Latin scripts); it is never invented for Latin-script languages where
 * spelling≠sound in non-obvious ways. Example sentences are only attached
 * when the sentence genuinely contains the word.
 */
final class VocabularyBank
{
    private const BANK = [
        'nl' => [
            ['hallo', 'hello', null, 'Hallo, ik heet Anna.', 'greetings', 'A1'],
            ['goedemorgen', 'good morning', null, null, 'greetings', 'A1'],
            ['dank je wel', 'thank you', null, null, 'courtesy', 'A1'],
            ['tot ziens', 'goodbye', null, null, 'courtesy', 'A1'],
            ['ik', 'I', null, null, 'people', 'A1'],
            ['vijf', 'five', null, null, 'numbers', 'A1'],
            ['een', 'one', null, null, 'numbers', 'A1'],
            ['het huis', 'the house', null, null, 'places', 'A1'],
            ['de stad', 'the city', null, null, 'places', 'A2'],
            ['de afspraak', 'the appointment', null, null, 'everyday', 'A2'],
        ],
        'es' => [
            ['hola', 'hello', null, null, 'greetings', 'A1'],
            ['buenos días', 'good morning', null, null, 'greetings', 'A1'],
            ['gracias', 'thank you', null, null, 'courtesy', 'A1'],
            ['adiós', 'goodbye', null, null, 'courtesy', 'A1'],
            ['yo', 'I', null, null, 'people', 'A1'],
            ['seis', 'six', null, null, 'numbers', 'A1'],
            ['siete', 'seven', null, null, 'numbers', 'A1'],
            ['ocho', 'eight', null, null, 'numbers', 'A1'],
            ['el pueblo', 'the town / village', null, null, 'places', 'A2'],
            ['la cita', 'the appointment', null, null, 'everyday', 'A2'],
        ],
        'fr' => [
            ['bonjour', 'hello / good day', null, null, 'greetings', 'A1'],
            ['merci', 'thank you', null, null, 'courtesy', 'A1'],
            ['au revoir', 'goodbye', null, null, 'courtesy', 'A1'],
            ['oui', 'yes', null, null, 'basics', 'A1'],
            ['non', 'no', null, null, 'basics', 'A1'],
            ['nous', 'we', null, null, 'people', 'A1'],
            ['quatre', 'four', null, null, 'numbers', 'A1'],
            ['deux', 'two', null, null, 'numbers', 'A1'],
            ['la ville', 'the city', null, null, 'places', 'A2'],
            ['un rendez-vous', 'an appointment', null, null, 'everyday', 'A2'],
        ],
        'de' => [
            ['hallo', 'hello', null, null, 'greetings', 'A1'],
            ['guten Morgen', 'good morning', null, null, 'greetings', 'A1'],
            ['danke', 'thank you', null, null, 'courtesy', 'A1'],
            ['tschüss', 'bye', null, null, 'courtesy', 'A1'],
            ['ich', 'I', null, null, 'people', 'A1'],
            ['ja', 'yes', null, null, 'basics', 'A1'],
            ['nein', 'no', null, null, 'basics', 'A1'],
            ['drei', 'three', null, null, 'numbers', 'A1'],
            ['die Stadt', 'the city', null, null, 'places', 'A2'],
            ['der Termin', 'the appointment', null, null, 'everyday', 'A2'],
        ],
        'it' => [
            ['buongiorno', 'good morning / hello', null, null, 'greetings', 'A1'],
            ['grazie', 'thank you', null, null, 'courtesy', 'A1'],
            ['arrivederci', 'goodbye', null, null, 'courtesy', 'A1'],
            ['io', 'I', null, null, 'people', 'A1'],
            ['sì', 'yes', null, null, 'basics', 'A1'],
            ['no', 'no', null, null, 'basics', 'A1'],
            ['tre', 'three', null, null, 'numbers', 'A1'],
            ['cinque', 'five', null, null, 'numbers', 'A1'],
            ['la città', 'the city', null, null, 'places', 'A2'],
            ["l'appuntamento", 'the appointment', null, null, 'everyday', 'A2'],
        ],
        'pt' => [
            ['bom dia', 'good morning', null, null, 'greetings', 'A1'],
            ['obrigado', 'thank you (m. speaker)', null, null, 'courtesy', 'A1'],
            ['adeus', 'goodbye', null, null, 'courtesy', 'A1'],
            ['eu', 'I', null, null, 'people', 'A1'],
            ['sim', 'yes', null, null, 'basics', 'A1'],
            ['não', 'no', null, null, 'basics', 'A1'],
            ['dois', 'two', null, null, 'numbers', 'A1'],
            ['seis', 'six', null, null, 'numbers', 'A1'],
            ['a cidade', 'the city', null, null, 'places', 'A2'],
            ['o compromisso', 'the appointment', null, null, 'everyday', 'A2'],
        ],
        'en' => [
            ['hello', 'hello', null, null, 'greetings', 'A1'],
            ['thank you', 'thank you', null, null, 'courtesy', 'A1'],
            ['goodbye', 'goodbye', null, null, 'courtesy', 'A1'],
            ['I', 'I', null, null, 'people', 'A1'],
            ['yes', 'yes', null, null, 'basics', 'A1'],
            ['no', 'no', null, null, 'basics', 'A1'],
            ['three', 'three', null, null, 'numbers', 'A1'],
            ['seven', 'seven', null, null, 'numbers', 'A1'],
            ['the city', 'the city', null, null, 'places', 'A1'],
            ['an appointment', 'an appointment', null, null, 'everyday', 'A2'],
        ],
        'sw' => [
            ['habari', 'hello (greeting)', null, null, 'greetings', 'A1'],
            ['asante', 'thank you', null, null, 'courtesy', 'A1'],
            ['kwaheri', 'goodbye', null, null, 'courtesy', 'A1'],
            ['karibu', 'welcome', null, null, 'courtesy', 'A1'],
            ['moja', 'one', null, null, 'numbers', 'A1'],
            ['mbili', 'two', null, null, 'numbers', 'A1'],
            ['tatu', 'three', null, null, 'numbers', 'A1'],
            ['jina', 'name', null, 'Jina langu ni Amina.', 'people', 'A1'],
            ['nyumba', 'house', null, null, 'places', 'A1'],
            ['maji', 'water', null, null, 'food-drink', 'A1'],
        ],
        'yo' => [
            ['báwo ni?', 'how are you?', null, null, 'greetings', 'A1'],
            ['ẹ ṣe', 'thank you', null, null, 'courtesy', 'A1'],
            ['ọ dàbọ̀', 'goodbye', null, null, 'courtesy', 'A1'],
            ['ọ̀kan', 'one', null, null, 'numbers', 'A1'],
            ['èjì', 'two', null, null, 'numbers', 'A1'],
            ['ẹ̀ta', 'three', null, null, 'numbers', 'A1'],
            ['ilé', 'house / home', null, null, 'places', 'A1'],
            ['omí', 'water', null, null, 'food-drink', 'A1'],
            ['owó', 'money', null, null, 'everyday', 'A1'],
            ['ọjọ́', 'day', null, null, 'time', 'A1'],
        ],
        'ig' => [
            ['ndewo', 'hello', null, null, 'greetings', 'A1'],
            ['daalụ', 'thank you', null, null, 'courtesy', 'A1'],
            ['ka ọ dị', 'goodbye (for now)', null, null, 'courtesy', 'A1'],
            ['otu', 'one', null, null, 'numbers', 'A1'],
            ['abụọ', 'two', null, null, 'numbers', 'A1'],
            ['atọ', 'three', null, null, 'numbers', 'A1'],
            ['ụlọ', 'house', null, null, 'places', 'A1'],
            ['mmiri', 'water', null, null, 'food-drink', 'A1'],
            ['ego', 'money', null, null, 'everyday', 'A1'],
            ['ụbọchị', 'day', null, null, 'time', 'A1'],
        ],
        'ha' => [
            ['sannu', 'hello', null, null, 'greetings', 'A1'],
            ['na gode', 'thank you', null, null, 'courtesy', 'A1'],
            ['sai anjima', 'see you tomorrow (bye)', null, null, 'courtesy', 'A1'],
            ['daya', 'one', null, null, 'numbers', 'A1'],
            ['biyu', 'two', null, null, 'numbers', 'A1'],
            ['uku', 'three', null, null, 'numbers', 'A1'],
            ['gida', 'house / home', null, null, 'places', 'A1'],
            ['ruwa', 'water', null, null, 'food-drink', 'A1'],
            ['kudi', 'money', null, null, 'everyday', 'A1'],
            ['rana', 'day / sun', null, null, 'time', 'A1'],
        ],
        'af' => [
            ['goeie dag', 'good day / hello', null, null, 'greetings', 'A1'],
            ['dankie', 'thank you', null, null, 'courtesy', 'A1'],
            ['totsiens', 'goodbye', null, null, 'courtesy', 'A1'],
            ['asseblief', 'please', null, null, 'courtesy', 'A1'],
            ['een', 'one', null, null, 'numbers', 'A1'],
            ['twee', 'two', null, null, 'numbers', 'A1'],
            ['drie', 'three', null, null, 'numbers', 'A1'],
            ['huis', 'house', null, null, 'places', 'A1'],
            ['water', 'water', null, null, 'food-drink', 'A1'],
            ['stad', 'city', null, 'My naam is Pieter.', 'places', 'A1'],
        ],
        'zu' => [
            ['sawubona', 'hello (one person)', null, null, 'greetings', 'A1'],
            ['ngiyabonga', 'I thank you', null, null, 'courtesy', 'A1'],
            ['sala kahle', 'goodbye (to one staying)', null, null, 'courtesy', 'A1'],
            ['kunye', 'one', null, null, 'numbers', 'A1'],
            ['kubili', 'two', null, null, 'numbers', 'A1'],
            ['kuthathu', 'three', null, null, 'numbers', 'A1'],
            ['indlu', 'house', null, null, 'places', 'A1'],
            ['amanzi', 'water', null, null, 'food-drink', 'A1'],
            ['imali', 'money', null, null, 'everyday', 'A1'],
            ['usuku', 'day', null, null, 'time', 'A1'],
        ],
        'ar' => [
            ['مرحبا', 'hello', 'marhaban', null, 'greetings', 'A1'],
            ['شكرا', 'thank you', 'shukran', null, 'courtesy', 'A1'],
            ['مع السلامة', 'goodbye', "ma'a as-salama", null, 'courtesy', 'A1'],
            ['اسمي', 'my name', 'ismī', 'اسمي أحمد', 'people', 'A1'],
            ['واحد', 'one', 'wāḥid', null, 'numbers', 'A1'],
            ['اثنان', 'two', 'ithnān', null, 'numbers', 'A1'],
            ['ثلاثة', 'three', 'thalātha', null, 'numbers', 'A1'],
            ['بيت', 'house', 'bayt', null, 'places', 'A1'],
            ['ماء', 'water', "mā'", null, 'food-drink', 'A1'],
            ['يوم', 'day', 'yawm', null, 'time', 'A1'],
        ],
        'zh' => [
            ['你好', 'hello', 'nǐ hǎo', null, 'greetings', 'A1'],
            ['谢谢', 'thank you', 'xièxie', null, 'courtesy', 'A1'],
            ['再见', 'goodbye', 'zàijiàn', null, 'courtesy', 'A1'],
            ['请', 'please', 'qǐng', null, 'courtesy', 'A1'],
            ['一', 'one', 'yī', null, 'numbers', 'A1'],
            ['二', 'two', 'èr', null, 'numbers', 'A1'],
            ['三', 'three', 'sān', null, 'numbers', 'A1'],
            ['家', 'home / family', 'jiā', null, 'places', 'A1'],
            ['水', 'water', 'shuǐ', null, 'food-drink', 'A1'],
            ['天', 'day / sky', 'tiān', null, 'time', 'A1'],
        ],
        'ja' => [
            ['こんにちは', 'hello (daytime)', 'konnichiwa', null, 'greetings', 'A1'],
            ['ありがとう', 'thank you', 'arigatō', null, 'courtesy', 'A1'],
            ['さようなら', 'goodbye', 'sayōnara', null, 'courtesy', 'A1'],
            ['はい', 'yes', 'hai', null, 'basics', 'A1'],
            ['いいえ', 'no', 'iie', null, 'basics', 'A1'],
            ['一', 'one', 'ichi', null, 'numbers', 'A1'],
            ['二', 'two', 'ni', null, 'numbers', 'A1'],
            ['三', 'three', 'san', null, 'numbers', 'A1'],
            ['家', 'house / home', 'ie', null, 'places', 'A1'],
            ['水', 'water', 'mizu', null, 'food-drink', 'A1'],
        ],
        'ko' => [
            ['안녕하세요', 'hello', 'annyeonghaseyo', null, 'greetings', 'A1'],
            ['감사합니다', 'thank you', 'gamsahamnida', null, 'courtesy', 'A1'],
            ['네', 'yes', 'ne', null, 'basics', 'A1'],
            ['아니요', 'no', 'aniyo', null, 'basics', 'A1'],
            ['하나', 'one', 'hana', null, 'numbers', 'A1'],
            ['둘', 'two', 'dul', null, 'numbers', 'A1'],
            ['셋', 'three', 'set', null, 'numbers', 'A1'],
            ['집', 'house / home', 'jip', null, 'places', 'A1'],
            ['물', 'water', 'mul', null, 'food-drink', 'A1'],
            ['날', 'day', 'nal', null, 'time', 'A1'],
        ],
        'ru' => [
            ['привет', 'hi', 'privet', null, 'greetings', 'A1'],
            ['спасибо', 'thank you', 'spasibo', null, 'courtesy', 'A1'],
            ['до свидания', 'goodbye', 'do svidaniya', null, 'courtesy', 'A1'],
            ['пожалуйста', 'please / you are welcome', 'pozhaluysta', null, 'courtesy', 'A1'],
            ['один', 'one', 'odin', null, 'numbers', 'A1'],
            ['два', 'two', 'dva', null, 'numbers', 'A1'],
            ['три', 'three', 'tri', null, 'numbers', 'A1'],
            ['дом', 'house / home', 'dom', null, 'places', 'A1'],
            ['вода', 'water', 'voda', null, 'food-drink', 'A1'],
            ['день', 'day', "den'", null, 'time', 'A1'],
        ],
        'hi' => [
            ['नमस्ते', 'hello / greetings', 'namaste', null, 'greetings', 'A1'],
            ['धन्यवाद', 'thank you', 'dhanyavaad', null, 'courtesy', 'A1'],
            ['अलविदा', 'goodbye', 'alvida', null, 'courtesy', 'A1'],
            ['नाम', 'name', 'naam', 'मेरा नाम राम है', 'people', 'A1'],
            ['एक', 'one', 'ek', null, 'numbers', 'A1'],
            ['दो', 'two', 'do', null, 'numbers', 'A1'],
            ['तीन', 'three', 'teen', null, 'numbers', 'A1'],
            ['घर', 'house / home', 'ghar', null, 'places', 'A1'],
            ['पानी', 'water', 'paani', null, 'food-drink', 'A1'],
            ['दिन', 'day', 'din', null, 'time', 'A1'],
        ],
        'tr' => [
            ['merhaba', 'hello', null, null, 'greetings', 'A1'],
            ['teşekkürler', 'thanks', null, null, 'courtesy', 'A1'],
            ['hoşça kal', 'goodbye', null, null, 'courtesy', 'A1'],
            ['lütfen', 'please', null, null, 'courtesy', 'A1'],
            ['bir', 'one', null, null, 'numbers', 'A1'],
            ['iki', 'two', null, null, 'numbers', 'A1'],
            ['üç', 'three', null, null, 'numbers', 'A1'],
            ['ev', 'house / home', null, null, 'places', 'A1'],
            ['su', 'water', null, null, 'food-drink', 'A1'],
            ['gün', 'day', null, null, 'time', 'A1'],
        ],
    ];

    /** @return array<int, array{word:string,translation:string,pronunciation:?string,example:?string,category:string,level:string}> */
    public static function items(string $lang): array
    {
        $out = [];
        foreach (self::BANK[strtolower(trim($lang))] ?? [] as $t) {
            $out[] = ['word' => $t[0], 'translation' => $t[1], 'pronunciation' => $t[2], 'example' => $t[3], 'category' => $t[4], 'level' => $t[5]];
        }
        return $out;
    }

    public static function count(string $lang): int
    {
        return count(self::BANK[strtolower(trim($lang))] ?? []);
    }
}
