-- SQLite mirror of lottery.mysql.sql.
-- WINDELS Lottery Intelligence: provider-neutral, source-attributed records.
CREATE TABLE IF NOT EXISTS lotteries (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, rules_version TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS lottery_rules (id INTEGER PRIMARY KEY AUTOINCREMENT, lottery_code TEXT NOT NULL, version TEXT NOT NULL, main_count INTEGER NOT NULL, main_min INTEGER NOT NULL, main_max INTEGER NOT NULL, star_count INTEGER NOT NULL, star_min INTEGER NOT NULL, star_max INTEGER NOT NULL, schedule TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, UNIQUE(lottery_code, version));
CREATE TABLE IF NOT EXISTS lottery_data_sources (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_code TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 0, synthetic INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS lottery_provider_health (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, status TEXT NOT NULL, response_ms INTEGER, records_received INTEGER NOT NULL DEFAULT 0, invalid_records INTEGER NOT NULL DEFAULT 0, error_rate REAL, last_success_at TEXT, last_failure_at TEXT, last_draw_retrieved TEXT, data_freshness_seconds INTEGER, synthetic INTEGER NOT NULL DEFAULT 0, observed_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_lottery_provider_health ON lottery_provider_health(provider_id, observed_at);
CREATE TABLE IF NOT EXISTS lottery_draws (id INTEGER PRIMARY KEY AUTOINCREMENT, lottery_code TEXT NOT NULL, provider_id INTEGER, external_id TEXT NOT NULL, draw_date TEXT NOT NULL, jackpot TEXT, rollover INTEGER NOT NULL DEFAULT 0, source TEXT NOT NULL, source_timestamp TEXT NOT NULL, retrieved_at TEXT NOT NULL, verification_status TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(lottery_code, external_id));
CREATE INDEX IF NOT EXISTS idx_lottery_draws_date ON lottery_draws(lottery_code, draw_date);
CREATE INDEX IF NOT EXISTS idx_lottery_draws_status ON lottery_draws(verification_status);
CREATE TABLE IF NOT EXISTS lottery_draw_numbers (id INTEGER PRIMARY KEY AUTOINCREMENT, draw_id INTEGER NOT NULL, kind TEXT NOT NULL, position INTEGER NOT NULL, number INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_lottery_draw_numbers_draw ON lottery_draw_numbers(draw_id, kind, position);
CREATE TABLE IF NOT EXISTS lottery_sync_runs (id TEXT PRIMARY KEY, provider_id INTEGER, job_type TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, ended_at TEXT, records_processed INTEGER NOT NULL DEFAULT 0, records_created INTEGER NOT NULL DEFAULT 0, records_updated INTEGER NOT NULL DEFAULT 0, errors TEXT, payload TEXT, execution_key TEXT NOT NULL UNIQUE);
CREATE INDEX IF NOT EXISTS idx_lottery_sync_runs_job ON lottery_sync_runs(job_type, started_at);
CREATE TABLE IF NOT EXISTS lottery_combinations (id INTEGER PRIMARY KEY AUTOINCREMENT, lottery_code TEXT NOT NULL, mode TEXT NOT NULL, model_version TEXT NOT NULL, seed TEXT, line_count INTEGER NOT NULL DEFAULT 0, lines TEXT NOT NULL, constraints TEXT NOT NULL, score_summary TEXT NOT NULL, created_by INTEGER, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_lottery_combinations_code ON lottery_combinations(lottery_code, created_at);
CREATE TABLE IF NOT EXISTS lottery_ai_decisions (id INTEGER PRIMARY KEY AUTOINCREMENT, lottery_code TEXT NOT NULL, combination_id INTEGER, model_version TEXT NOT NULL, mode TEXT, decision TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_lottery_ai_decisions_comb ON lottery_ai_decisions(combination_id);
CREATE TABLE IF NOT EXISTS lottery_tickets (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, lottery_code TEXT NOT NULL, name TEXT NOT NULL, draw_date TEXT, generation_method TEXT NOT NULL, model_version TEXT NOT NULL, configuration TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'OPEN', result TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_lottery_tickets_user ON lottery_tickets(user_id, status);
CREATE TABLE IF NOT EXISTS lottery_ticket_lines (id INTEGER PRIMARY KEY AUTOINCREMENT, ticket_id INTEGER NOT NULL, position INTEGER NOT NULL, mains TEXT NOT NULL, stars TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_lottery_ticket_lines_ticket ON lottery_ticket_lines(ticket_id, position);
CREATE TABLE IF NOT EXISTS lottery_backtests (id INTEGER PRIMARY KEY AUTOINCREMENT, lottery_code TEXT NOT NULL, strategy TEXT NOT NULL, model_version TEXT NOT NULL, lines_per_draw INTEGER NOT NULL DEFAULT 1, draws_tested INTEGER NOT NULL DEFAULT 0, period_from TEXT, period_to TEXT, dataset_version TEXT, report TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_lottery_backtests_strategy ON lottery_backtests(strategy, created_at);
CREATE TABLE IF NOT EXISTS lottery_model_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, model_name TEXT NOT NULL, model_version TEXT NOT NULL, config TEXT NOT NULL, dataset_version TEXT, status TEXT NOT NULL DEFAULT 'ACTIVE', created_at TEXT NOT NULL, UNIQUE(model_name, model_version));
