-- SQLite mirror of sports_decisions.mysql.sql.
CREATE TABLE IF NOT EXISTS sports_model_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, model_name TEXT NOT NULL, model_version TEXT NOT NULL, feature_version TEXT NOT NULL, calibration_version TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(model_name, model_version));
CREATE TABLE IF NOT EXISTS sports_predictions (id TEXT PRIMARY KEY, match_id INTEGER NOT NULL, model_version_id INTEGER NOT NULL, market TEXT NOT NULL, selection TEXT NOT NULL, raw_probability REAL, calibrated_probability REAL, implied_probability REAL, expected_value REAL, confidence REAL, risk TEXT NOT NULL, correlation TEXT NOT NULL, data_quality_score INTEGER NOT NULL, decision TEXT NOT NULL, rejection_reasons TEXT, factors TEXT NOT NULL, input_version TEXT NOT NULL, odds REAL, odds_timestamp TEXT, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sports_predictions_match ON sports_predictions(match_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sports_predictions_model ON sports_predictions(model_version_id, created_at);
CREATE TABLE IF NOT EXISTS sports_tickets (id TEXT PRIMARY KEY, created_at TEXT NOT NULL, model_version_id INTEGER, configuration_version TEXT NOT NULL, total_odds REAL, selection_count INTEGER NOT NULL, combined_probability REAL, confidence REAL, risk TEXT NOT NULL, correlation TEXT NOT NULL, data_quality_score INTEGER, status TEXT NOT NULL, approval_status TEXT NOT NULL, settlement_status TEXT NOT NULL, reason TEXT, stake REAL, pnl REAL);
CREATE INDEX IF NOT EXISTS idx_sports_tickets_status ON sports_tickets(status, created_at);
CREATE TABLE IF NOT EXISTS sports_ticket_selections (id INTEGER PRIMARY KEY AUTOINCREMENT, ticket_id TEXT NOT NULL, prediction_id TEXT NOT NULL, match_id INTEGER NOT NULL, market TEXT NOT NULL, selection TEXT NOT NULL, odds REAL NOT NULL, odds_timestamp TEXT NOT NULL, model_probability REAL, calibrated_probability REAL, expected_value REAL, risk TEXT NOT NULL, result TEXT, status TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sports_ticket_selections_ticket ON sports_ticket_selections(ticket_id);
CREATE INDEX IF NOT EXISTS idx_sports_ticket_selections_prediction ON sports_ticket_selections(prediction_id);
