-- SQLite mirror of sports.mysql.sql.
CREATE TABLE IF NOT EXISTS sports_data_sources (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_code TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sports_provider_health (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, status TEXT NOT NULL, response_ms INTEGER, error_rate REAL, rate_limit_remaining INTEGER, last_success_at TEXT, last_failure_at TEXT, last_fixture_sync_at TEXT, last_odds_sync_at TEXT, last_result_sync_at TEXT, data_freshness_seconds INTEGER, records_received INTEGER NOT NULL DEFAULT 0, invalid_records INTEGER NOT NULL DEFAULT 0, missing_fields TEXT, observed_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_provider_health ON sports_provider_health(provider_id, observed_at);
CREATE TABLE IF NOT EXISTS sports_matches (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, external_id TEXT NOT NULL, sport TEXT NOT NULL, competition TEXT NOT NULL, home_team TEXT NOT NULL, away_team TEXT NOT NULL, kickoff_at TEXT NOT NULL, status TEXT NOT NULL, source_timestamp TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id, external_id));
CREATE INDEX IF NOT EXISTS idx_sports_matches_kickoff ON sports_matches(kickoff_at);
CREATE INDEX IF NOT EXISTS idx_sports_matches_status ON sports_matches(status);
CREATE TABLE IF NOT EXISTS sports_odds (id INTEGER PRIMARY KEY AUTOINCREMENT, match_id INTEGER NOT NULL, provider_id INTEGER NOT NULL, market TEXT NOT NULL, selection TEXT NOT NULL, decimal_odds REAL NOT NULL, observed_at TEXT NOT NULL, payload TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sports_odds_match_market ON sports_odds(match_id, market, observed_at);
CREATE TABLE IF NOT EXISTS sports_data_quality_assessments (id INTEGER PRIMARY KEY AUTOINCREMENT, match_id INTEGER NOT NULL, score INTEGER NOT NULL, band TEXT NOT NULL, freshness_score INTEGER NOT NULL, provider_reliability_score INTEGER NOT NULL, eligible_prediction INTEGER NOT NULL, eligible_ticket INTEGER NOT NULL, missing_fields TEXT NOT NULL, checks_payload TEXT NOT NULL, assessed_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sports_quality_match ON sports_data_quality_assessments(match_id, assessed_at);
CREATE TABLE IF NOT EXISTS sports_sync_runs (id TEXT PRIMARY KEY, provider_id INTEGER, job_type TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, ended_at TEXT, records_processed INTEGER NOT NULL DEFAULT 0, records_created INTEGER NOT NULL DEFAULT 0, records_updated INTEGER NOT NULL DEFAULT 0, errors TEXT, execution_key TEXT NOT NULL UNIQUE);
CREATE INDEX IF NOT EXISTS idx_sports_sync_runs_job ON sports_sync_runs(job_type, started_at);
